services:
  frontend:
    platform: linux/amd64  # Specify platform explicitly
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.yourdomain.com # Production API URL
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  portfolio-network:
    driver: bridge