services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    init: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - TINI_SUBREAPER=true 
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000