name: Docker Build and Deploy

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     
     - name: Build and push
       uses: docker/build-push-action@v4
       with:
         context: ./frontend
         push: true
         tags: |
           ghcr.io/tomichi/portfolio:latest
           ghcr.io/tomichi/portfolio:${{ github.sha }}
         cache-from: type=gha
         cache-to: type=gha,mode=max

     - name: Security scan
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: ghcr.io/tomichi/portfolio:${{ github.sha }}
         format: 'table'
         ignore-unfixed: true
         severity: 'CRITICAL'
         vuln-type: 'os,library'
         exit-code: '0'

     - name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}